baseURL = "https://sebthecat.com/"
languageCode = "en-us"
title = "Seb The Cat"
theme = "bootstrap4"
paginate = 10
summaryLength = 50
uglyurls = true
copyright = "&copy; Copyright Comyune Technologies Ltd, 2020"
googleAnalytics = "UA-168657035-1"
disqusShortname = "seb-the-cats-blog"

[related]
threshold = 10
includeNewer = false
toLower = true
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name = "date"
weight = 10

[permalinks]
  posts = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCnKdHNJCqjXIWB5-U7PTazQ"

[[menu.sidebar]]
  name = "Twitch"
  url = "https://twitch.tv/comyune"

[[menu.sidebar]]
  name = "Comyune"
  url = "https://comyune.com"

[[menu.sidebar]]
  name = "DevBrett"
  url = "https://devbrett.com"

[[menu.navbar]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCnKdHNJCqjXIWB5-U7PTazQ"

[[menu.navbar]]
  name = "Twitch"
  url = "https://twitch.tv/comyune"

[[menu.navbar]]
  name = "Comyune"
  url = "https://comyune.com"

# Theme variables
[params]
  author = "Seb The Cat"
  description = "A blog chronicling Seb's journey in development for pawsterity."
  header_visible = true
  date_format = "Mon Jan 02, 2006"
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  #cookie_consent_info_url = "/cookie-information/"
  #cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  sharingicons = true

  # Display post summaries instead of content in list templates (default: true)
  truncate = false

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    about = "Seb is a feline tussled by the world who has run away from his human family. Making ends meet by building a little kitty empire on the web."
    num_recent_posts = 10

  [params.social]
    # Optional, used for attribution in Twitter cards (ideally not a person
    # for example: nytimes, flickr, NatGeo, etc).
    # See: https://dev.twitter.com/cards/types/summary-large-image
    twitter = "sebthecat"








