baseURL = "https://sebthecat.com/"
languageCode = "en-us"
title = "Seb The Cat"
theme = "bootstrap4"
paginate = 10
summaryLength = 100
uglyurls = true
copyright = "&copy; Copyright Comyune Technologies Ltd, 2020"
googleAnalytics = "UA-168657035-1"
disqusShortname = "seb-the-cats-blog"

[related]
threshold = 5
includeNewer = true
toLower = true
[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name = "date"
weight = 10

[permalinks]
  posts = "/:year/:month/:title/"
  page = "/:slug/"

[[menu.sidebar]]
  name = "Portfolio"
  url = "https://devbrett.com"
  weight = 9

[[menu.sidebar]]
  name = "Twitter"
  url = "https://twitter.com/_SebTheCat_"
  weight = 1

[[menu.sidebar]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCVQ2Rt-GlX3ptQ94GUtulmQ"
  weight = 1

[[menu.sidebar]]
  name = "Twitch"
  url = "https://twitch.tv/sebthecat_com"
  weight = 2

[[menu.navbar]]
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCVQ2Rt-GlX3ptQ94GUtulmQ"

[[menu.navbar]]
  name = "Twitch"
  url = "https://twitch.tv/sebthecat_com"

[[menu.navbar]]
  name = "Twitter"
  url = "https://twitter.com/_SebTheCat_"

# Theme variables
[params]
  author = "Seb The Cat"
  description = "A blog chronicling Seb's journey in development for pawsterity."
  header_visible = true
  date_format = "Mon Jan 02, 2006"
  #google_verify_meta = "BAi57DROASu4b2mkVNA_EyUsobfA7Mq8BmSg7Rn-Zp9"
  #bing_verify_meta = "3DA353059F945D1AA256B1CD8A3DA847"
  #yandex_verify_meta = "66b077430f35f04a"

  # Optionally display a message about the site's use of cookies, which may be
  # required for your site in the European Union. Set the parameter below to a
  # page where the user can get more information about cookies, either on your
  # site or externally, for example:
  # cookie_consent_info_url = "/cookie-information/"
  # cookie_consent_info_url = "http://cookiesandyou.com"

  # show sharing icons on pages/posts (default: true)
  sharingicons = false # true

  # Display post summaries instead of content in list templates (default: true)
  truncate = true

  # Disable the use of sub-resource integrity on CSS/JS assets (default: false)
  # Useful if you're using a CDN or other host where you can't control cache headers
  #disable_sri = false

  [params.sidebar]
    about = "Seb is a feline tussled by the world. He has run away from his human family and making ends meet by teaching software and art on the web."
    num_recent_posts = 20

  [markup.goldmark.renderer]
    unsafe = true

  [params.social]
    twitter = "_SebTheCat_"
