name: Publish

on: { push: { branches: [ master ] } }

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: { submodules: true, fetch-depth: 0 }
    
    - name: Prepare Submodules
      run: git submodule init && git submodule update

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with: { hugo-version: '0.74.1', extended: true }

    - name: Build
      run: HUGO_ENV=production hugo --minify --debug --log --verbose --verboseLog

    # - name: Hugo Broken Link Check
    #   uses: marccampbell/hugo-linkcheck-action@v0.1.3
    #   env: { HUGO_ACTION_COMMENT: 0 }

    - name: S3 Sync
      uses: jakejarvis/s3-sync-action@v0.5.1
      with: { args: "--acl public-read --follow-symlinks" }
      env:
        AWS_S3_BUCKET: sebthecat.com
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-west-2'
        SOURCE_DIR: 'public'